name: uee_project
description: "FoodLink - AI-Powered Food Redistribution Platform"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  google_sign_in: ^6.1.5
  image_picker: ^1.0.4
  qr_flutter: ^4.1.0
  firebase_messaging: ^14.7.9
  google_maps_flutter: ^2.5.0
  geolocator: ^11.1.0
  flutter_local_notifications: ^17.2.1
  camera: ^0.10.5
  path_provider: ^2.1.1
  flutter_secure_storage: ^9.0.0
  pull_to_refresh: ^2.0.0
  connectivity_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
